dist: trusty
env:
  global:
    - TF_VERSION=0.11.1
    - SHELLCHECK_VERSION="0.7.0"

before_install:
  - |
    mkdir ~/bin
    export PATH=~/bin:$PATH
  - |
    echo "Fetching shellcheck"
    wget -qO- "https://storage.googleapis.com/shellcheck/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" | tar -xJv
    cp "shellcheck-v${SHELLCHECK_VERSION}/shellcheck" ~/bin
  - |
    echo "Fetching Terraform"
    set -e
    wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    unzip -o terraform_${TF_VERSION}_linux_amd64.zip -d ~/bin
    rm terraform_${TF_VERSION}_linux_amd64.zip
  - pip install --user yamllint
  - GIMME_OUTPUT=$(gimme 1.13 | tee -a $HOME/.bashrc) && eval "$GIMME_OUTPUT"
  - export GOPATH=$HOME/gopath
  - export PATH=$HOME/gopath/bin:$PATH
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega/...
  - go get -u github.com/alphagov/paas-cf/tools/pipecleaner

script:
  - make test
